# Generated by Django 5.2.4 on 2025-08-20 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largo', models.IntegerField()),
                ('team', models.CharField(max_length=8)),
                ('color', models.CharField(max_length=10)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penes', to='app.personita')),
            ],
        ),
    ]
